[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[features]
default = []
simd = ["portable_simd"]
portable_simd = []

[dependencies]
rand = "0.8.5"
rayon = "1.7"
wgpu = "0.19" # 版本以 crates.io 为准
pollster = "0.3"
indicatif = "0.17"
crossbeam = "0.8"
image = "0.24"